const WA_NUMBER="";243986238968
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const levels=[
["A1","Débutant","🌱",true,"Fondations et communication quotidienne"],
["A2","Élémentaire","🌿",true,"Situations courantes et grammaire de base"],
["B1","Intermédiaire","🚀",true,"Autonomie, opinions et expériences"],
["B2","Intermédiaire supérieur","⭐",false,"Argumentation et précision"],
["C1","Avancé","🏆",false,"Nuances et expression structurée"],
["C2","Maîtrise","👑",false,"Maîtrise et compréhension fine"]];
const titles={
A1:["Salutations","Se présenter","Famille","Nombres","Couleurs","Objets","Maison","Nourriture","Boissons","Dates","Heure","École","Travail","Ville","Transports","Météo","Vêtements","Corps","Goûts","Questions","Verbe be","Présent simple","There is/are","Can/can’t","Révision"],
A2:["Routine","Habitudes","Maison","Achats","Restaurant","Voyage","Aéroport","Hôtel","Santé","Loisirs","Sports","Médias","Téléphone","Relations","Travail","Projets","Passé simple","Futur","Comparatifs","Quantités","Présent continu","Present perfect","Modaux","Connecteurs","Révision"],
B1:["Opinions","Expériences","Objectifs","Travail","Études","Voyage","Actualité","Technologie","Environnement","Relations","Émotions","Solutions","Conseils","Hypothèses","Present perfect","Past continuous","Future forms","Conditionnels","Phrasal verbs","Expressions","Messages","Présentation","Débat","Compréhension","Révision"],
B2:["Argumenter","Nuancer","Société","Économie","Science","Technologie","Environnement","Éducation","Management","Culture","Médias","Idiomes","Collocations","Discours indirect","Voix passive","Conditionnels","Modaux au passé","Relatives","Registre","Essai","Présentation","Débat","Compréhension","Synthèse","Révision"],
C1:["Nuances","Argumentation","Actualité","Économie","Recherche","IA","Environnement","Institutions","Arts","Carrière","Leadership","Communication","Idiomes","Collocations","Inversion","Cleft sentences","Subjonctif","Académique","Écriture","Synthèse","Analyse","Présentation","Débat","Compréhension","Révision"],
C2:["Lexique","Registres","Humour","Métaphores","Rhétorique","Discours","Littérature","Presse","Sciences humaines","Recherche","Droit","Économie","Technologie","Identité","Idiomes rares","Collocations","Syntaxe","Style","Académique","Professionnel","Analyse","Débat expert","Compréhension","Production","Révision"]};
const words=[["hello","bonjour"],["book","livre"],["learn","apprendre"],["speak","parler"],["friend","ami"],["house","maison"],["work","travail"],["food","nourriture"],["water","eau"],["time","temps"],["school","école"],["travel","voyager"]];
const grammar={A1:"Le présent simple parle des habitudes et faits : I work. Avec he/she/it : She works.",A2:"Le passé simple décrit une action terminée : I visited my friend yesterday.",B1:"Le present perfect relie une expérience au présent : I have visited London.",B2:"Les conditionnels expriment des hypothèses : If I had time, I would study.",C1:"Nuance une idée avec however, although, nevertheless et arguably.",C2:"Le registre, les collocations et la syntaxe permettent une expression très précise."};
let s=JSON.parse(localStorage.getItem("jolearn_state")||"null")||{onboard:false,name:"Joseph",language:"Anglais",level:"A1",goal:"Voyage",xp:0,coins:0,lives:5,streak:0,lessons:0,daily:0,dark:false,done:[]};
let step=0,ti=0,score=0,currentLevel="",currentLesson=0;
const test=[["What is hello?",["Bonjour","Merci","Livre"],0],["I ___ a student.",["am","is","are"],0],["book = ?",["Livre","Maison","Table"],0],["She ___ English.",["speak","speaks","speaking"],1],["thank you = ?",["Pardon","Merci","Salut"],1]];
const save=()=>localStorage.setItem("jolearn_state",JSON.stringify(s));
function boot(){setTimeout(()=>{$("#splash").remove();s.onboard?showApp():showOnboard()},700)}
const selected=(t,v)=>t==="language"?s.language===v:t==="goal"?s.goal===v:t==="level"?s.choice===v:false;
function showOnboard(){let d=[
["Bienvenue sur JoLearn 👋","Une vraie plateforme : 6 niveaux, 25 leçons par niveau, vocabulaire, phrases, expressions, grammaire et quiz.","welcome"],
["Quelle langue ?","Le parcours actuel est optimisé pour l’anglais.","language",[["🇬🇧","Anglais"],["🇫🇷","Français"],["🇪🇸","Espagnol"],["🇩🇪","Allemand"]]],
["Quel est ton niveau ?","Le test proposera aussi un niveau.","level",[["🌱","Débutant total"],["🌿","Quelques connaissances"],["🚀","Intermédiaire"]]],
["Pourquoi apprends-tu ?","Choisis ton objectif.","goal",[["✈️","Voyage"],["💼","Travail"],["🎓","Études"],["🗣️","Communication"]]],
["Test de placement 🧠","5 questions.","test"]][step];
$("#onboard").classList.remove("hidden");$("#op").style.width=((step+1)/5*100)+"%";
let h="<h2>"+d[0]+"</h2><p>"+d[1]+"</p>";
if(d[2]==="welcome")h+='<div class="choices"><div class="choice sel">🎯 <b>150 leçons structurées</b></div></div>';
if(d[3])h+='<div class="choices">'+d[3].map((x,i)=>`<button class="choice ${selected(d[2],x[1])?"sel":""}" data-c="${i}">${x[0]} &nbsp; <b>${x[1]}</b></button>`).join("")+"</div>";
if(d[2]==="test"){let q=test[ti];h=`<h2>${d[0]}</h2><p>${d[1]}</p><div class="card"><b>Question ${ti+1}/5</b><h3>${q[0]}</h3>${q[1].map((x,i)=>`<button class="quizOpt" data-t="${i}">${x}</button>`).join("")}</div>`}
$("#oc").innerHTML=h;
$$("[data-c]").forEach(b=>b.onclick=()=>{let x=d[3][+b.dataset.c][1];if(d[2]==="language")s.language=x;if(d[2]==="goal")s.goal=x;if(d[2]==="level")s.choice=x;showOnboard()});
if(d[2]==="test")$$("[data-t]").forEach(b=>b.onclick=()=>{let q=test[ti],i=+b.dataset.t;$$("[data-t]").forEach(x=>x.disabled=true);if(i===q[2])score++;setTimeout(()=>{ti++;if(ti<5)showOnboard();else{s.level=score>=4?"A2":"A1";s.onboard=true;delete s.choice;save();showApp()}},350)});
$("#onext").onclick=()=>{if(d[2]!=="test"){step++;showOnboard()}};
}
function showApp(){$("#onboard").classList.add("hidden");$("#app").classList.remove("hidden");update();page("home")}
function update(){let L=levels.find(x=>x[0]===s.level)||levels[0];$("#hello").textContent="Bonjour "+s.name+" 👋";$("#goal").textContent="Objectif : "+s.goal;$("#hl").textContent=L[0]+" · "+L[1];$("#hp").textContent=s.lessons+" leçon(s) terminée(s)";$("#hxp").textContent=s.xp+" XP";$("#streak").textContent=s.streak;$("#coins").textContent=s.coins;$("#lives").textContent=s.lives;$("#daily").textContent=Math.min(s.daily,50)+"/50 XP";$("#db").style.width=Math.min(s.daily/50*100,100)+"%";$("#pn").textContent=s.name;$("#pl").textContent=L[0]+" · "+L[1];$("#px").textContent=s.xp;$("#pc").textContent=s.coins;$("#pm").textContent=s.lessons;homeLessons();renderLevels()}
function homeLessons(){let a=titles[s.level],start=Math.min(s.lessons,20),arr=a.slice(start,start+5);if(arr.length<5)arr=a.slice(0,5);$("#homeLessons").innerHTML=arr.map((t,j)=>{let i=a.indexOf(t),done=s.done.includes(s.level+"-"+i);return `<div class="courseItem ${done?"done":""}"><div class="icon">${done?"✓":"📘"}</div><div><h3>Leçon ${i+1} · ${t}</h3><p>Vocabulaire · phrases · grammaire · quiz</p></div><button data-open="${i}">${done?"Revoir":"Commencer"}</button></div>`}).join("");$$("[data-open]").forEach(b=>b.onclick=()=>openLesson(s.level,+b.dataset.open))}
function renderLevels(){$("#levels").innerHTML=levels.map(l=>`<div class="level"><div class="num">${l[2]}</div><div><h3>${l[0]} · ${l[1]}</h3><p>25 leçons · ${l[3]?"Gratuit":"🔒 Premium"}</p></div><button data-l="${l[0]}">${l[3]?"Voir":"🔒"}</button></div>`).join("");$$("[data-l]").forEach(b=>b.onclick=()=>openCourse(b.dataset.l))}
function openCourse(id){let L=levels.find(x=>x[0]===id);if(!L[3])return premium();currentLevel=id;$("#course").classList.remove("hidden");$("#ct").textContent=id+" · "+L[1];$("#cs").textContent="25 leçons · "+L[4];$("#lessons").innerHTML=titles[id].map((t,i)=>{let d=s.done.includes(id+"-"+i);return `<div class="lessonItem ${d?"done":""}"><div class="num">${d?"✓":i+1}</div><div><h3>Leçon ${i+1} · ${t}</h3><p>📚 vocabulaire · 💬 phrases · 📖 grammaire · 🧠 quiz</p></div><button data-li="${i}">${d?"Revoir":"Commencer"}</button></div>`}).join("");$$("[data-li]").forEach(b=>b.onclick=()=>openLesson(id,+b.dataset.li))}
$("#see").onclick=()=>page("learn");$("#backCourse").onclick=()=>$("#course").classList.add("hidden");$("#backLesson").onclick=()=>$("#lesson").classList.add("hidden");
function openLesson(level,i){currentLevel=level;currentLesson=i;let t=titles[level][i],a=words[(i*2)%words.length],b=words[(i*2+1)%words.length];$("#lesson").classList.remove("hidden");$("#lt").textContent="Leçon "+(i+1)+" · "+t;$("#ls").textContent=level;$("#vocab").innerHTML=[a,b,words[(i+3)%words.length],words[(i+5)%words.length]].map(w=>`<div class="word"><b>${w[0]}</b><small>${w[1]}</small></div>`).join("");$("#phrases").innerHTML=`<div class="phrase">I am learning English.</div><div class="phrase">Can you use <b>${a[0]}</b> in a sentence?</div>`;$("#expr").innerHTML='<div class="expr"><b>Keep going!</b><br>Continue, ne baisse pas les bras.</div>';$("#gram").textContent=grammar[level];let opts=Math.random()>.5?[a[0],b[0]]:[b[0],a[0]];$("#lq").textContent="Que signifie « "+a[0]+" » ?";$("#lo").innerHTML=opts.map(x=>`<button class="quizOpt" data-a="${x===a[0]}">${x}</button>`).join("");$("#lf").textContent="";$("#finish").classList.add("hidden");$$("[data-a]").forEach(x=>x.onclick=()=>answerLesson(x))}
function answerLesson(x){$$("[data-a]").forEach(b=>b.disabled=true);if(x.dataset.a==="true"){x.classList.add("good");$("#lf").textContent="🎉 Correct !";$("#finish").classList.remove("hidden")}else{x.classList.add("bad");$("#lf").textContent="❌ Mauvaise réponse. Une vie est retirée.";s.lives=Math.max(0,s.lives-1);save();setTimeout(()=>openLesson(currentLevel,currentLesson),600)}}
$("#finish").onclick=()=>{let k=currentLevel+"-"+currentLesson;if(!s.done.includes(k)){s.done.push(k);s.lessons++;s.xp+=10;s.coins+=3;s.daily+=10}save();update();$("#lesson").classList.add("hidden");$("#course").classList.add("hidden");alert("🎉 Leçon terminée ! +10 XP et +3 pièces")};
function page(n){["home","learn","quiz","bot","profile"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==n));$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.p===n));if(n==="quiz")newQuiz();if(n==="bot"&&!$("#chat").children.length)addMsg("bot","Bonjour ! Je suis JoBot 🤖. Écris une phrase en anglais.")}
$$("nav button").forEach(b=>b.onclick=()=>page(b.dataset.p));$$("[data-p]").forEach(b=>b.onclick=()=>page(b.dataset.p));
const qd=[["Good morning = ?",["Bonjour","Bonsoir","Merci"],0],["I ___ English.",["study","studies","studying"],0],["book = ?",["Livre","Maison","École"],0],["She ___ happy.",["are","am","is"],2]];let cq;
function newQuiz(){cq=qd[Math.floor(Math.random()*qd.length)];$("#qq").textContent=cq[0];$("#qf").textContent="";$("#qn").classList.add("hidden");$("#qo").innerHTML=cq[1].map((x,i)=>`<button class="quizOpt" data-q="${i}">${x}</button>`).join("");$$("[data-q]").forEach(b=>b.onclick=()=>{let i=+b.dataset.q;$$("[data-q]").forEach(x=>x.disabled=true);if(i===cq[2]){$("#qf").textContent="🎉 Correct ! +5 XP";b.classList.add("good");s.xp+=5;s.coins++;s.daily+=5}else{$("#qf").textContent="❌ Bonne réponse : "+cq[1][cq[2]];b.classList.add("bad");s.lives=Math.max(0,s.lives-1)}save();update();$("#qn").classList.remove("hidden")})}
$("#qn").onclick=newQuiz;
function addMsg(w,t){let d=document.createElement("div");d.className="msg "+w;d.textContent=t;$("#chat").appendChild(d);$("#chat").scrollTop=$("#chat").scrollHeight}function send(){let t=$("#ci").value.trim();if(!t)return;addMsg("user",t);$("#ci").value="";setTimeout(()=>addMsg("bot",t.toLowerCase().includes("yesterday")&&t.toLowerCase().includes("go")?"Correction : Yesterday, I went…":"Bonne tentative 👍. JoBot local peut être relié à une vraie API IA ensuite."),250)}$("#send").onclick=send;$("#ci").onkeydown=e=>e.key==="Enter"&&send();
$("#dark").onclick=()=>{s.dark=!s.dark;document.body.classList.toggle("dark",s.dark);save()};$("#reset").onclick=()=>{if(confirm("Réinitialiser ?")){localStorage.removeItem("jolearn_state");location.reload()}};$("#wa").onclick=()=>WA_NUMBER?location.href="https://wa.me/"+WA_NUMBER:alert("Ajoute ton numéro dans WA_NUMBER dans app.js.");
document.body.classList.toggle("dark",s.dark);boot();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
